kind: pipeline
name: default

steps:
- name: build
  image: microsoft/dotnet:2.2-sdk
  commands:
  - dotnet restore "k8s-app/k8s-app.csproj"
  - dotnet build "k8s-app/k8s-app.csproj"

- name: publish  
  image: plugins/docker
  settings:
    registry: reg.qiniu.com
    repo: reg.qiniu.com/platosoft/k8s-app
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD

trigger:
  branch:
  - master